bounds:
  name: bounds
  description: The southwest and northeast corners of the bounding box in WGS84 decimal degrees, in the format `swlat,swlng|nelat,nelng`. Latitude must be in the interval [-90, 90] and longitude must be in the interval [-180, 180]. `swlat` must be less than `nelat`, but `swlng` can be larger than `nelng` if the box crosses the line of 180 degrees longitude.
  in: query
  explode: false
  style: pipeDelimited
  required: true
  schema:
    type: array
    minItems: 2
    maxItems: 2
    items:
      type: array
      minItems: 2
      maxItems: 2
      items:
        type: number
        minimum: -180
        maximum: 180
    example: [[-5, -180], [5, 180]]
zoom:
  name: zoom
  description: Zoom level, where the world is divided into a 2<sup>zoom</sup> x 2<sup>zoom</sup> grid.
  in: query
  schema:
    type: integer
    minimum: 0
    maximum: 14
    default: 0
muni:
  name: muni
  description: Whether to include Locations imported from municipal tree inventories.
  in: query
  schema:
    type: boolean
    default: true
types:
  name: types
  description: IDs of Types to include (all by default).
  in: query
  explode: false
  schema:
    type: array
    uniqueItems: true
    items:
      type: integer
      minimum: 0
    default: null
invasive:
  name: invasive
  description: Whether to only return Locations with Types locally flagged as invasive species. Note that this parameter is not supported for filtering clusters.
  in: query
  schema:
    type: boolean
    default: false
location_id:
  name: id
  in: path
  description: Location ID.
  required: true
  schema:
    type: integer
    minimum: 1
type_id:
  name: id
  in: path
  description: Type ID.
  required: true
  schema:
    type: integer
    minimum: 1
review_id:
  name: id
  in: path
  description: Review ID.
  required: true
  schema:
    type: integer
    minimum: 1
user_id:
  name: id
  in: path
  description: User ID.
  required: true
  schema:
    type: integer
    minimum: 1
import_id:
  name: id
  in: path
  description: Import ID.
  required: true
  schema:
    type: integer
    minimum: 1
recaptcha:
  name: g-recaptcha-response
  in: header
  description: |
    User response token for a Google reCAPTCHA v2 (see https://developers.google.com/recaptcha/docs/verify).
    May be passed as a header or query parameter, or in the request body.
    Only required if user authentication (if available for the endpoint) is not provided.
  required: false
  schema:
    type: string
    minLength: 1
    nullable: false
offset:
  name: offset
  in: query
  description: Offset from which to apply `limit`.
  schema:
    type: integer
    minimum: 0
    default: 0
    nullable: false
